cargo-features = ["edition2024"]

[package]
name = "pw-hashing-rust"
version = "0.2.2"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = "*"
rand_core = { version = "*", features = ["getrandom"] }
colored = "*"
zeroize = "*"
futures = "*"
passwords = { version = "3.1.16", features = ["common-password"] }
rayon = "*"
log = "*"
thiserror = "*"
rand = "*"


[profile.release]
opt-level = 3
debug = false
lto = "thin"
codegen-units = 1