cargo-features = ["edition2024"]

[package]
name = "pw-hashing-rust"
version = "0.2.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = "*"
rand_core = { version = "*", features = ["getrandom"] }
colored = "*"
zeroize = "*"
rpassword = "*"
log = "*"

[profile.release]
opt-level = 3
debug = false
lto = true
